services:
  app:
    image: entourage:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:Y3WjwtOEoBN39N5fRsgO@entourage-database-db-1:5432/entourage?schema=public
    ports:
      - "4521:80"
    networks:
      - entouragelab.com
    restart: always

networks:
  entouragelab.com:
    external: true
